# ------------------------------------------------------------------------------
#     Languages
# ------------------------------------------------------------------------------

# The comments have become "episodic" and been moved to: RK32 OpenAI Supported Languages.json

# Probably, this is the only official list of supported languages as of 2024-03-28:
# https://platform.openai.com/docs/guides/text-to-speech
# Shouldnt hurt to start with it, then.

class OpenAiLanguage(enum.Enum):
    AFRIKAANS = "afrikaans"
    ARABIC = "arabic"
    ARMENIAN = "armenian"
    AZERBAIJANI = "azerbaijani"
    BELARUSIAN = "belarusian"
    BOSNIAN = "bosnian"
    BULGARIAN = "bulgarian"
    CATALAN = "catalan"
    CHINESE = "chinese"
    CROATIAN = "croatian"
    CZECH = "czech"
    DANISH = "danish"
    DUTCH = "dutch"
    ENGLISH = "english"
    ESTONIAN = "estonian"
    FINNISH = "finnish"
    FRENCH = "french"
    GALICIAN = "galician"
    GERMAN = "german"
    GREEK = "greek"
    HEBREW = "hebrew"
    HINDI = "hindi"
    HUNGARIAN = "hungarian"
    ICELANDIC = "icelandic"
    INDONESIAN = "indonesian"
    ITALIAN = "italian"
    JAPANESE = "japanese"
    KANNADA = "kannada"
    KAZAKH = "kazakh"
    KOREAN = "korean"
    LATVIAN = "latvian"
    LITHUANIAN = "lithuanian"
    MACEDONIAN = "macedonian"
    MALAY = "malay"
    MARATHI = "marathi"
    MAORI = "maori"
    NEPALI = "nepali"
    NORWEGIAN = "norwegian"
    PERSIAN = "persian"
    POLISH = "polish"
    PORTUGUESE = "portuguese"
    ROMANIAN = "romanian"
    RUSSIAN = "russian"
    SERBIAN = "serbian"
    SLOVAK = "slovak"
    SLOVENIAN = "slovenian"
    SPANISH = "spanish"
    SWAHILI = "swahili"
    SWEDISH = "swedish"
    TAGALOG = "tagalog"
    TAMIL = "tamil"
    THAI = "thai"
    TURKISH = "turkish"
    UKRAINIAN = "ukrainian"
    URDU = "urdu"
    VIETNAMESE = "vietnamese"
    WELSH = "welsh"
